# Análise de Acidentes nas Rodovias da Bahia - PRF

Este notebook explora os dados abertos da [Polícia Rodoviária Federal (PRF)](https://www.gov.br/prf/pt-br/acesso-a-informacao/dados-abertos/dados-abertos-da-prf), referentes aos registros de acidentes agrupados por pessoa, de 2019 a 2025.

O objetivo é investigar os acidentes ocorridos nas rodovias do estado da Bahia, utilizando os dados nacionais para selecionar os registros correspondentes ao estado.

## Importação das bibliotecas utilizadas no Projeto:

In [1]:
import pandas as pd

Os arquivos `.csv` de dados de acidentes da PRF estão estruturados com valores separados por **ponto e vírgula** `;`, o que justifica o parâmetro `sep=';'`

Esses arquivos utilizam o formato numérico **brasileiro**. Significa que os números decimais são separados por **vírgula** `,` ao invés de **ponto** `.`. O que justifica o uso do parâmetro `decimal=','`

Além disso, há acentuação e caracteres especiais no idioma brasileiro, justificando o uso de `encoding='latin-1'` (ou _encoding='cp1252'_). Já que a utilização do formato _UTF-8_, apresentou o erro `byte 0xe1`.

## Exemplo de carregamento de dados (csv 2025):

In [2]:
# Lendo o csv de 2025
df = pd.read_csv("../data/raw/acidentes2025.csv", sep=';', decimal=',', encoding='latin-1')

# df = pd.read_csv("../data/raw/acidentes2025.csv", sep=';', decimal=',', encoding='utf-8')
# Caso o comentário da linha acima seja removido, o código apresentará erro devido à utilização do 'utf-8'

df.head()

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,652493,1467686,2025-01-01,quarta-feira,06:20:00,SP,116,225.0,GUARULHOS,Reação tardia ou ineficiente do condutor,...,Não Informado,0,0,0,0,-23.485868,-46.540753,SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,1467833,2025-01-01,quarta-feira,07:50:00,CE,116,546.2,PENAFORTE,Pista esburacada,...,Masculino,1,0,0,0,-7.812288,-39.083333,SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,1468042,2025-01-01,quarta-feira,08:45:00,PR,369,88.2,CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,...,Masculino,1,0,0,0,-23.182565,-50.637228,SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,1467849,2025-01-01,quarta-feira,11:00:00,PR,116,74.0,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,...,Masculino,1,0,0,0,-25.365177,-49.042230,SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,1467791,2025-01-01,quarta-feira,09:30:00,MG,251,471.0,FRANCISCO SA,Velocidade Incompatível,...,Masculino,1,0,0,0,-16.468013,-43.431213,SPRF-MG,DEL12-MG,UOP01-DEL12-MG

## Contagem de Linhas e Colunas:

In [3]:
qtd = []
total_lin = 0  # Variável que conta o total de linhas

# Loop de leitura dos CSVs
for ano in range(2019, 2026):
    path = f"../data/raw/acidentes{ano}.csv"  # Automatizando a mudança de arquivo CSV
    df_ano = pd.read_csv(path, sep=';', decimal=',', encoding='latin-1')
    
    # Adicionando as informações (ano, linhas e colunas) à lista
    qtd.append({
        "Ano": ano,
        "Linhas": df_ano.shape[0],
        "Colunas": df_ano.shape[1]
    })

# Transformando as listas em um DataFrame e definindo o index
escopo = pd.DataFrame(qtd).set_index("Ano")
print(f"{escopo['Linhas'].sum()} Linhas Totais")
escopo

1249899 Linhas Totais

      Linhas  Colunas
Ano
2019  176104       35
2020  162245       35
2021  166287       35
2022  170825       35
2023  183361       35
2024  196448       35
2025  194629       35

## Carregando a base de dados completa:

Concatenando todos os dados (2019 a 2025) em um único DataFrame e adicionando a coluna **ano** a cada um dos conjuntos de dados, para facilitar a identificação.

Agora, o novo DataFrame (`df`) deve conter **1249899** linhas × **36 colunas**

In [4]:
# Lista que armazenará o conjunto de DataFrames
lista = []

# Loop de leitura dos CSVs
for ano in range(2019, 2026):
    path = f"../data/raw/acidentes{ano}.csv"  # Automatizando a mudança de arquivo CSV

    df_ano = pd.read_csv(path, sep=';', decimal=',', encoding='latin-1')
    df_ano['ano'] = ano  # Adicionando a coluna 'ano'

    lista.append(df_ano)

df = pd.concat(lista, ignore_index=True)  # Transformando a lista de DataFrames em um DataFrame único
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop,ano
0,182256.0,403856,2019-01-01,terça-feira,04:00:00,CE,116,136.9,RUSSAS,Animais na Pista,...,1,0,0,0,-4.766018,-38.056034,SPRF-CE,DEL03-CE,UOP01-DEL03-CE,2019
1,182263.0,402859,2019-01-01,terça-feira,05:00:00,MT,158,599.5,AGUA BOA,Defeito Mecânico no Veículo,...,1,0,0,0,-14.319000,-52.169000,SPRF-MT,DEL07-MT,UOP02-DEL07-MT,2019
2,182277.0,402850,2019-01-01,terça-feira,10:00:00,PA,10,34.0,DOM ELISEU,Velocidade Incompatível,...,1,0,0,0,-4.152967,-47.546082,SPRF-PA,DEL02-PA,UOP02-DEL02-PA,2019
3,182289.0,402431,2019-01-01,terça-feira,08:30:00,BA,101,13.0,RIO REAL,Ingestão de Álcool,...,1,0,0,0,-11.589600,-37.876100,SPRF-SE,DEL02-SE,UOP03-DEL02-SE,2019
4,182307.0,402638,2019-01-01,terça-feira,13:50:00,BA,116,440.0,FEIRA DE SANTANA,Ingestão de Álcool,...,0,1,0,0,-12.344000,-39.087000,SPRF-BA,DEL02-BA,UOP01-DEL02-BA,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1249894,757593.0,1701493,2025-12-14,domingo,13:50:00,PE,104,62.0,CARUARU,Ausência de reação do condutor,...,1,0,0,0,-8.253680,-35.975460,SPRF-PE,DEL02-PE,UOP01-DEL02-PE,2025
1249895,758175.0,1702860,2025-12-15,segunda-feira,15:50:00,SC,101,130.0,CAMBORIU,Condutor deixou de manter distância do veículo...,...,1,0,0,0,-26.993060,-48.660955,SPRF-SC,DEL04-SC,UOP03-DEL04-SC,2025
1249896,758175.0,1702859,2025-12-15,segunda-feira,15:50:00,SC,101,130.0,CAMBORIU,Condutor deixou de manter distância do veículo...,...,1,0,0,0,-26.993060,-48.660955,SPRF-SC,DEL04-SC,UOP03-DEL04-SC,2025
1249897,758186.0,1702906,2025-11-02,domingo,23:00:00,MG,381,218.3,BELO ORIENTE,Acessar a via sem observar a presença dos outr...,...,0,0,1,0,-19.298811,-42.371921,SPRF-MG,DEL06-MG,UOP01-DEL06-MG,2025
1249898,758186.0,1702905,2025-11-02,domingo,23:00:00,MG,381,218.3,BELO ORIENTE,Acessar a via sem observar a presença dos outr...,...,1,0,0,0,-19.298811,-42.371921,SPRF-MG,DEL06-MG,UOP01-DEL06-MG,2025

## Confirmando que há um único index no DF geral:

In [5]:
df.index.is_unique

True

## Padronização do tipo da coluna `id`

A coluna de ID do DataFrame geral foi lida com o formato de número **decimal**, quando deveriam ser números **inteiros**, de acordo com o dicionário de dados da PRF.

Ao analisar todos os arquivos de acidentes, é possível notar que apenas os CSVs dos anos de 2022, 2023 e 2025 possuem a coluna 'id' com o formato `int64`, sendo que as demais apresentam o formato `float64`.

In [6]:
print("ANO | COLUNA 'id'\n")

# Loop para automatizar a leitura dos arquivos
for ano in range(2019, 2026):
    caminho = f"../data/raw/acidentes{ano}.csv"
    df_ano = pd.read_csv(caminho, sep=';', decimal=',', encoding='latin-1')
    print(ano, df_ano['id'].dtype)  # Retorna o TIPO da coluna 'id' em seu respectivo 'ano'

ANO | COLUNA 'id'

2019 float64
2020 float64
2021 float64
2022 int64
2023 int64
2024 float64
2025 int64

## Identificando se não há nulos na coluna `id`:

In [7]:
# Retornando a soma de valores nulos na coluna de ID
print(df["id"].isna().sum())

0

## Confirmando que todos os valores de ID são originalmente Inteiros:

In [8]:
# Se todos os restos de divisão por 1 forem 0, então podemos ignorar as casas decimais de todos os valores
print((df["id"] % 1 == 0).all())

True

## Convertendo a coluna 'id' de `float64` (decimal) para `int64` (inteiro):
Como a célula acima confirma que nenhum dos IDs são decimais, a fim de gerar uma padronização, a coluna 'id' será convertida para valores inteiros.

In [9]:
df['id'] = df['id'].astype("int64")
df['id'].dtype

dtype('int64')

## Quantas Linhas e quantos Acidentes por ano?
PS: _**Linhas** = linhas por ano_ | _**Acidentes** = IDs por ano_

In [10]:
# Agrupando as linhas por 'ano' e aplicando função de agregação
df.groupby('ano').agg(
    Linhas = ('id', 'size'),  # Coluna 'Linhas': Seleciona a coluna 'id' e conta as linhas totais
    Acidentes = ('id', 'nunique')  # Coluna 'Acidentes': Seleciona a coluna 'id' e conta os valores distintos para cada ano
)

      Linhas  Acidentes
ano
2019  176104      67558
2020  162245      63585
2021  166287      64567
2022  170825      64606
2023  183361      67766
2024  196448      73202
2025  194629      72529

De acordo com o resultado acima, em todos os anos a quantidade de linhas totais é cerca de **2,6 a 2,7 vezes** a quantidade de `Acidentes`. Ex: _(2019) 176104 / 67558 ≈ 2,6067_

Portanto, uma linha representa uma **pessoa**, e não um acidente. Logo, o número de acidentes é calculado por `COUNT (DISTINCT id)`, por exemplo, nunca pelo total de linhas em um ano.

## Analisando o tipo de dado das colunas `km`, `latitude` e `longitude`

In [11]:
# Selecionando as colunas e retornando os tipos (dtypes)
df[['km', 'latitude', 'longitude']].dtypes

km           float64
latitude     float64
longitude    float64
dtype: object

In [12]:
# Analisando como esses dados foram armazenados no DataFrame geral
df[['km', 'latitude', 'longitude']].head()

      km   latitude  longitude
0  136.9  -4.766018 -38.056034
1  599.5 -14.319000 -52.169000
2   34.0  -4.152967 -47.546082
3   13.0 -11.589600 -37.876100
4  440.0 -12.344000 -39.087000

Nos datasets originais da PRF, o separador decimal dos números nas 3 colunas utilizadas acima é a **vírgula** `,`, correspondendo ao formato numérico brasileiro.

Porém, na leitura dos arquivos, utilizando o parâmetro `decimal=','`, o Pandas já os converteu para `float64`. Sendo assim, os números decimais do DataFrame geral agora utilizam **ponto** `.` como separador, indicando que o parâmetro utilizado funcionou.

## Quais colunas possuem Nulos e quantos são, por Ano?

In [13]:
# Soma dos Nulos por tipo, agrupado por Ano e com os eixos invertidos (colunas viraram linhas)
nulos = df.isna().groupby(df['ano']).sum().T
# Exclui as linhas onde não há nenhum nulo
nulos[nulos.sum(axis=1) > 0]

ano                      2019   2020   2021   2022   2023   2024   2025
tipo_acidente              32      1      0      0      0      0      0
classificacao_acidente      9      4      7      3      3      3      7
tipo_veiculo             7011   6307   6254   6642   6685   6598   6341
tipo_envolvido          13604  14488  15313  15439  16428  17201  17150
estado_fisico           13604  14488  15313  15439  16428  17201  17150
sexo                    13604  14488  15313  15439  16428  17201  17150
regional                    8      0      0     37     48      0      6
delegacia                 121     64     57     85    100     79     74
uop                       130    131    103    169    141    190    130

Essa tabela demonstra que há valores **nulos** dentre as informações de: `tipo_acidente`, `classificacao_acidente`, `tipo_veiculo`, `tipo_envolvido`, `estado_fisico`, `sexo`, `regional`, `delegacia` e `uop`.

Inclusive, é possível notar que os valores nulos se repetem, a cada ano, nas colunas de `tipo_envolvido`, `estado_fisico` e `sexo`, o que será analisado mais adiante.

## Os nulos de `tipo_envolvido`, `estado_fisico` e `sexo` estão nas mesmas linhas?

É necessário conferir isso, já que, apesar de apresentarem as mesmas quantidades em todos os anos, a distribuição desses valores dentre as colunas pode ser diferente.

In [14]:
# Seleciona apenas as colunas a serem comparadas
col_nulos = df[['tipo_envolvido', 'estado_fisico', 'sexo']]

# Conferindo as linhas onde os valores das 3 colunas são nulos
val_1 = col_nulos.isna().all(axis=1).sum()
# Conferindo as linhas onde, pelo menos, 1 dos valores das 3 colunas é nulo
val_2 = col_nulos.isna().any(axis=1).sum()

print('Os valores são iguais?', val_1 == val_2)
print(val_1, val_2)

Os valores são iguais? True
109623 109623

In [15]:
# Utilizando a tabela 'nulos', criada acima, para comparar a quantidade de valores nulos
print(nulos.loc['tipo_envolvido'].sum())

109623

Utilizando `.all(axis=1).sum()` e `.any(axis=1).sum()`, obtive **109.623** em ambos os casos.

A lógica foi comparar a quantidade de linhas em que as três colunas são nulas simultaneamente (`all`) com a quantidade de linhas em que pelo menos uma delas é nula (`any`). Após isso, também comparei com o total de valores nulos na tabela "nulos".

Como os resultados foram iguais, concluí que os valores nulos de `tipo_envolvido`, `estado_fisico` e `sexo` estão exatamente nas mesmas linhas.